import { ReactNode } from "react";
import { NextIntlClientProvider } from "next-intl";
import { NotistackProvider } from '@/hooks/NotistackProvider';


import { Providers } from "@/app/providers"
import AppContext from '@/context/AppContext';


import { lexendDeca } from './../fonts';
import './globals.css';

export const metadata = {
  title: "PPD-Przemek-Wozniak",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
  argPublic: string;
  params: { locale: string };
};

const RootLayout: React.FC<RootLayoutProps> = ({
  children,
  params: { locale },
}) => {
  const messages = require(`@/messages/${locale}.json`);

  return (
    <Providers>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <html lang={locale} className={lexendDeca.variable}>
          <body className="box-border flex flex-col items-center overflow-x-hidden max-w-screen">
            <NotistackProvider>
             <AppContext>
              {children}
             </AppContext>
            </NotistackProvider>
         </body>
        </html>
      </NextIntlClientProvider>
    </Providers>
  );
};
export default RootLayout;


